stages:
- analysis

variables:
  GOPATH: '/runner-cache/zero'
  GOCACHE: '/runner-cache/zero'
  GOPROXY: 'https://goproxy.cn,direct'

analysis:
  stage: analysis
  image: golang
  script:
    - go version && go env
    - go test -short $(go list ./...) | grep -v "no test"
  only:
   - merge_requests
  tags:
    - common
